# Prima fase per la compilazione
FROM python:3.9-slim-bullseye AS compile-image

RUN apt-get update && apt-get install -y curl bash build-essential libffi-dev libpq-dev gfortran

RUN set -uex; \
    apt-get update; \
    apt-get install -y ca-certificates curl gnupg; \
    mkdir -p /etc/apt/keyrings; \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
     | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
    NODE_MAJOR=18; \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" \
     > /etc/apt/sources.list.d/nodesource.list; \
    apt-get -qy update; \
    apt-get -qy install nodejs;

ARG PIP_EXTRA_INDEX_URL=https://www.piwheels.org/simple

COPY ecologichome_src /ecologichome_src

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip3 install --upgrade pip && \
    pip3 install setuptools==62.4.0 && \
    pip3 install -e /ecologichome_src/ecologichome/ && \
    pip3 install appdaemon==4.2.1 

WORKDIR /ecologichome_src/frontend
RUN npm install && npm run build

FROM python:3.9-slim-bullseye AS build-image

RUN apt-get update && apt-get install -y curl bash libpq-dev nodejs cron

# Copia le dipendenze Python e Node.js dalla fase di compilazione
COPY --from=compile-image /opt/venv /opt/venv
COPY --from=compile-image /ecologichome_src /ecologichome_src

RUN apt-get update && apt-get install -y curl bash && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y libpq-dev nodejs cron

COPY --from=compile-image /opt/venv /opt/venv
COPY --from=compile-image /ecologichome_src /ecologichome_src


ENV PATH="/opt/venv/bin:$PATH"
WORKDIR /

ENTRYPOINT [ "bash", "/ecologichome_src/startup/run.sh" ]

