volumes:
  ecologichome_config:
    name: ecologichome_config
    external: true

services:
  ecologichome:
    container_name: ecologichome
    image: lightningpicture/aarch64-thesillyhome-dev:dev-30
    restart: unless-stopped
    volumes:
      - ecologichome_config:/ecologichome_src/data/config/
    ports:
      - 2300:2300
