version: '3'

services:
  ecologichome:
    container_name: ecologichome
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ecologichome_config:/ecologichome_src/data/config/
    ports:
      - 2300:2300

volumes:
  ecologichome_config:
    name: ecologichome_config
    external: true
