volumes:
  ecologichome_config:
    name: ecologichome_config
  ignore:
    name: ignore

services:
  ecologichome:
    container_name: ecologichome
    image: dadaloop82/aarch64-ecologichome-dev:dev-30
    restart: unless-stopped
    volumes:
      - .\ecologichome_src\appdaemon\apps\:/ecologichome_src/appdaemon/apps/
      - .\ecologichome_src\startup\:/ecologichome_src/startup/
      - .\ecologichome_src\ecologichome\:/ecologichome_src/ecologichome/
      - .\ecologichome_src\frontend\src\:/ecologichome_src/frontend/src/
      - ecologichome_config:/ecologichome_src/data/config/
    ports:
      - "2300:2300"
      - "3000:3000"
