FROM python:3.9-slim-bullseye AS compile-image

RUN apt-get update && apt-get install -y curl bash && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y \
    build-essential \
    libffi-dev \
    libpq-dev \
    nodejs \
    gfortran \
    git && \
    apt-get install -y libpq-dev nodejs cron

ARG PIP_EXTRA_INDEX_URL=https://www.piwheels.org/simple

RUN git clone https://github.com/dadaloop82/ecologichome-container.git /ecologichome_src
WORKDIR /ecologichome_src/

RUN pip3 install --upgrade pip && \
    pip3 install setuptools==62.4.0 && \
    pip3 install -r ecologichome/requirements.txt && \    
    pip3 install appdaemon==4.2.1


WORKDIR /ecologichome_src/frontend
RUN npm install && npm run build

FROM python:3.9-slim-bullseye AS build-image

COPY --from=compile-image /opt/venv /opt/venv
COPY --from=compile-image /ecologichome_src /ecologichome_src

ENV PATH="/opt/venv/bin:$PATH"
WORKDIR /

ENTRYPOINT [ "bash", "/ecologichome_src/startup/run.sh" ]
